### ISSUE TITLE
about the timer

### ISSUE THREAD

**Issue by vipmengfeng** [ndusart/ps2-keyboard#3]
Is ICR1=160 in the timer an error? Shouldn't 20us be ICR1=320?

**Comment by ndusart** [comment]
Yes, you are absolutely right. On Arduino Uno, the clock is running and 16MHz, so ICR1 should be 320 after 20us. Thanks for the report.

There is too long time since I read this code and I do not have PS/2 keyboard or computer with PS/2 port to test that. I cannot say why it worked with this error. Does it work on your side ?

**Comment by vipmengfeng** [comment]
Yes, I modified some code, and now it works. I don't know how the timer works in the PS2 protocol, but it's okay whether it's 20 or 10 microseconds or some other values. I tried to port the code to other chips and adapted the timer interrupt program of the chip. I succeeded on the seeedunio Xiao MCU using SAMD21 chip, but failed on the nrf52 series chips. It should be the timer interrupt problem. I am a new person on the single chip, so I don't know how to fix it.
~~~~~~
The code I modified like this: (In FidPS2Host.cpp and  FidPS2keyboard.cpp)
replace
       ```
        DDRD |= (1<<pin); // output
	PORTD &= ~(1<<pin); // low
```
with
	```
        pinMode(pin,OUTPUT);
	digitalWrite(pin, LOW);
```

I don't know why it does not work on my arduino except I replace the code，they work on the same principle，am I right?

**Comment by ndusart** [comment]
`pinMode` and `digitalWrite` should indeed have the same effect as writing directly into the port registers.

The way they can differ is that the register I used may be not the correct one for the given `pin`. The actual logic is written there: https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/wiring_digital.c

The mapping between pin numbers and port is listed here: https://github.com/arduino/ArduinoCore-avr/blob/9f8d27f09f3bbd1da1374b5549a82bda55d45d44/variants/standard/pins_arduino.h#L150

You can see that PORTD can only be used for the first 8 pins (as registers are 8-bit words on this uC), so if you used a pin higher than 7 the previous code would not work while arduino `digitalWrite` will.
